### ISSUE TITLE
Pip is not importing

### ISSUE THREAD

**Issue by Gui25Reis** [dfm/kepler.py#1]
Hello, I'm not able to download directly as `pip install`! Is giving this error `PEP 517`

A scientific initiation from a friend is in need of this program but we are unable to use it!

Is there any prerequisite on the machine to be able to use it?

Can you fix this?
Please, contact me!

![image](https://user-images.githubusercontent.com/48360732/102129882-da7d6200-3e2e-11eb-9b87-d5cca853a950.png)

**Comment by dfm** [comment]
The issue looks like it's with numpy not with this code so I'm not sure how much I can help in detail. But I will add a Windows binary for the next release.

**Comment by Gui25Reis** [comment]
Hmm OK

This morning I may be able to take a closer look at the problem. If not today, tomorrow

If I can fix it, I create a brench and comment what was fixed and return it!

We need it for our scientific initiation and since it is close to Christmas, we are speeding up because people travel.

But thank you very much for your feedback and congratulations on your work


Gui Reis


________________________________

**Comment by dfm** [comment]
I just published a new release that will include a Windows binary on PyPI. So, once [this job](https://github.com/dfm/kepler.py/actions/runs/421794762) finishes running you should be able to install using pip without compiling. Let me know!

**Comment by dfm** [comment]
PS if it doesn't work, please give me some more details about what you're doing. What version of Windows, Python, Conda/Anaconda(?), `pip`, etc. and exactly which commands you're running to install.

**Comment by Gui25Reis** [comment]
I got it!!!
It worked, thank you very much !!

Then if you want to take a look later on the initiation's [blog](https://www.starsandexoplanets.org/) (ps: it is in portuguese hehe)

Thank u so much!

**Comment by Gui25Reis** [comment]
I got it!!!
It worked, thank you very much !!

Then if you want to take a look later on the initiation's [blog](https://www.starsandexoplanets.org/) (ps: it is in portuguese hehe)

Thank u so much!
